"""Pure-Python nginx stream config file text generator.

No I/O — only produces text. The SSH service is responsible for writing
the generated text to the remote redirector.

File layout on the redirector:
    <nginx_stream_dir>/cyberx_<stream_id>.conf
        One server {} block per StreamConfig. For SNI-routed streams this
        is the "inner terminator" that listens on 127.0.0.1:<bridge_port>.
        For legacy (non-SNI) streams it's a public-facing block as before.

    <nginx_stream_dir>/cyberx_sni_<listen_port>.conf
        Per-(redirector, listen_port) "outer router" generated by
        generate_sni_router_config() whenever any SNI streams exist on
        that port. Contains a nginx `map` of $ssl_preread_server_name to
        127.0.0.1:<bridge_port>, plus the outer server {} that does the
        preread and proxy_pass.

    /etc/nginx/conf.d/cyberx_decoy.conf
        Generated by generate_decoy_http_config() once any SNI stream
        exists. Serves the maintenance HTML for unmatched SNI values on
        the loopback decoy port. Lives in http context, not stream.

The outer  stream { include ...; }  block and the http include of
/etc/nginx/conf.d/*.conf are both assumed to already exist in nginx.conf.
This service never touches nginx.conf.
"""
import re
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Iterable

if TYPE_CHECKING:
    from app.models.redirector import StreamConfig


_UNSAFE_NGINX_CHARS = frozenset("\n\r;{}")

_MAX_OVERRIDE_BYTES = 32 * 1024  # 32 KB ceiling — more than enough for any single stream file

# Loopback port range for SNI inner terminators on the redirector.
# 10999 is reserved for the decoy HTTP server so unmatched SNI has a
# place to land; 10000–10998 are the pool the allocator draws from.
SNI_BRIDGE_PORT_MIN = 10000
SNI_BRIDGE_PORT_MAX = 10998
SNI_DECOY_PORT = 10999

# Loopback IP all SNI-related binds use. Never leaks to the public NIC.
SNI_LOOPBACK_IP = "127.0.0.1"

# DNS label validator for sni_hostname. We require a plausibly valid
# hostname (letters/digits/dot/dash) and cap length at the DNS maximum,
# so the map key we emit can't contain anything unsafe. Underscores are
# not valid in public DNS, but some internal setups use them — allowed.
_SNI_HOSTNAME_RE = re.compile(r"^(?=.{1,253}$)[a-zA-Z0-9_]([a-zA-Z0-9_.-]*[a-zA-Z0-9_])?$")


def _safe_sni_hostname(val: str) -> str:
    """Validate a stream's sni_hostname before interpolating into nginx map."""
    if not isinstance(val, str) or not _SNI_HOSTNAME_RE.match(val):
        raise ValueError(f"Invalid sni_hostname: {val!r}")
    return val.lower()


def _safe_nginx_value(val: str, field_name: str) -> str:
    """Defense-in-depth: reject values that could break out of an nginx directive."""
    if any(c in _UNSAFE_NGINX_CHARS for c in val):
        raise ValueError(f"Unsafe character in {field_name}: {val!r}")
    return val


def validate_custom_override(text: str) -> None:
    """
    Cheap structural sanity check for a hand-edited stream config.

    This is NOT an nginx parser — nginx -t on the redirector is the
    authoritative check. We only guard against obviously malformed input
    and bytes that would be unsafe to write to disk or would clearly not
    be an nginx stream server block.

    Raises ValueError on failure.
    """
    if text is None:
        raise ValueError("Custom config must not be null.")
    if not isinstance(text, str):
        raise ValueError("Custom config must be a string.")
    if "\x00" in text:
        raise ValueError("Custom config contains a null byte.")
    encoded_len = len(text.encode("utf-8"))
    if encoded_len == 0:
        raise ValueError("Custom config must not be empty.")
    if encoded_len > _MAX_OVERRIDE_BYTES:
        raise ValueError(
            f"Custom config exceeds {_MAX_OVERRIDE_BYTES} bytes "
            f"({encoded_len} bytes provided)."
        )
    if "server" not in text or "{" not in text:
        raise ValueError(
            "Custom config must contain an nginx 'server { ... }' block."
        )
    # Balanced braces, ignoring braces inside '# ...' comment lines.
    depth = 0
    for line in text.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("#"):
            continue
        for ch in line:
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth < 0:
                    raise ValueError("Custom config has unbalanced braces (extra '}').")
    if depth != 0:
        raise ValueError("Custom config has unbalanced braces (missing '}').")


def generate_stream_config(stream: "StreamConfig") -> str:
    """
    Generate the content of a single nginx stream .conf file for a StreamConfig.

    Returns the complete text for cyberx_<stream_id>.conf. The file contains
    one server {} block — no outer stream {} wrapper.

    Override behaviour:
        If stream.custom_config_override is set, it is returned verbatim
        and the structured-field path is skipped entirely.

    SNI-routed branch (stream.sni_hostname set):
        Emits an "inner terminator" that listens only on
        127.0.0.1:<internal_bridge_port>, terminates TLS with the stream's
        cert, and bridges to cs_ip:cs_port. ACLs on SNI streams are handled
        at the outer router (see generate_sni_router_config), not here,
        because loopback connections from the preread router are always
        coming from 127.0.0.1 and per-stream ACL at this layer is moot.

    Legacy branch:
        tcp  — plain TCP proxy; optionally TLS bridging
        udp  — UDP proxy with reuseport
        dns  — UDP with proxy_responses 1
    """
    override = getattr(stream, "custom_config_override", None)
    if override:
        return override if override.endswith("\n") else override + "\n"

    if getattr(stream, "sni_hostname", None):
        return _generate_sni_inner_terminator(stream)

    return _generate_legacy_stream_block(stream)


def _generate_legacy_stream_block(stream: "StreamConfig") -> str:
    """Non-SNI path: one public-facing server block on listen_port."""
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    protocol = (stream.protocol or "tcp").lower()
    is_dns = protocol == "dns"
    is_udp = protocol in ("udp", "dns")

    safe_name = _safe_nginx_value(stream.name, "name")
    safe_cs_ip = _safe_nginx_value(stream.cs_ip, "cs_ip")

    lines: list[str] = [
        f"# CyberX Managed - {safe_name}",
        f"# Generated: {now_utc} - DO NOT EDIT MANUALLY",
        "",
        "server {",
    ]

    # --- listen directive --------------------------------------------------
    if is_udp:
        lines.append(f"    listen {stream.listen_port} udp reuseport;")
    elif stream.ssl_enabled and stream.ssl_cert_path and stream.ssl_key_path:
        lines.append(f"    listen {stream.listen_port} ssl;")
    else:
        lines.append(f"    listen {stream.listen_port};")

    # --- proxy_pass -------------------------------------------------------
    lines.append(f"    proxy_pass {safe_cs_ip}:{stream.cs_port};")

    # --- timeouts ---------------------------------------------------------
    if is_udp:
        lines.append("    proxy_timeout 20s;")
    else:
        lines.append("    proxy_connect_timeout 60s;")
        lines.append("    proxy_timeout 10m;")

    # --- DNS-specific -----------------------------------------------------
    if is_dns:
        lines.append("    proxy_responses 1;")

    # --- TLS bridging block (TCP only) ------------------------------------
    # Terminates the client TLS handshake on the redirector using the legit
    # cert, then opens a fresh TLS connection upstream so the CS team server
    # can keep its own self-signed cert. Without proxy_ssl on, nginx would
    # send plaintext to a TLS-expecting upstream and the connection would
    # be dropped immediately.
    if stream.ssl_enabled and not is_udp and stream.ssl_cert_path and stream.ssl_key_path:
        safe_cert = _safe_nginx_value(stream.ssl_cert_path, "ssl_cert_path")
        safe_key = _safe_nginx_value(stream.ssl_key_path, "ssl_key_path")
        safe_protocols = _safe_nginx_value(stream.ssl_protocols, "ssl_protocols")
        safe_ciphers = _safe_nginx_value(stream.ssl_ciphers, "ssl_ciphers")
        lines.append(f"    ssl_certificate {safe_cert};")
        lines.append(f"    ssl_certificate_key {safe_key};")
        lines.append(f"    ssl_protocols {safe_protocols};")
        lines.append(f"    ssl_ciphers {safe_ciphers};")
        lines.append("    ssl_session_cache shared:SSL:10m;")
        lines.append("    ssl_session_timeout 10m;")
        lines.append("    proxy_ssl on;")
        lines.append("    proxy_ssl_verify off;")

    # --- Access control ---------------------------------------------------
    if stream.access_control_enabled and stream.allowed_cidrs:
        for cidr in stream.allowed_cidrs:
            safe_cidr = _safe_nginx_value(cidr.strip(), "allowed_cidr")
            lines.append(f"    allow {safe_cidr};")
        lines.append("    deny all;")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _generate_sni_inner_terminator(stream: "StreamConfig") -> str:
    """
    SNI-routed path: inner terminator bound to 127.0.0.1:<bridge_port>.

    Requires stream.ssl_enabled, a cert/key path, and internal_bridge_port
    to be set. Raises ValueError if any precondition is missing so the
    caller never writes a half-formed file to the redirector.
    """
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    bridge_port = getattr(stream, "internal_bridge_port", None)
    if not bridge_port:
        raise ValueError(
            "SNI-routed stream requires internal_bridge_port to be allocated."
        )
    if not (SNI_BRIDGE_PORT_MIN <= int(bridge_port) <= SNI_BRIDGE_PORT_MAX):
        raise ValueError(
            f"internal_bridge_port {bridge_port} outside allowed range "
            f"{SNI_BRIDGE_PORT_MIN}-{SNI_BRIDGE_PORT_MAX}."
        )
    if not (stream.ssl_cert_path and stream.ssl_key_path):
        raise ValueError(
            "SNI-routed stream requires ssl_cert_path and ssl_key_path (the "
            "inner terminator must hold a cert to answer the TLS handshake)."
        )

    safe_name = _safe_nginx_value(stream.name, "name")
    safe_sni = _safe_sni_hostname(stream.sni_hostname)
    safe_cs_ip = _safe_nginx_value(stream.cs_ip, "cs_ip")
    safe_cert = _safe_nginx_value(stream.ssl_cert_path, "ssl_cert_path")
    safe_key = _safe_nginx_value(stream.ssl_key_path, "ssl_key_path")
    safe_protocols = _safe_nginx_value(stream.ssl_protocols, "ssl_protocols")
    safe_ciphers = _safe_nginx_value(stream.ssl_ciphers, "ssl_ciphers")

    lines = [
        f"# CyberX Managed - {safe_name} (SNI inner terminator for {safe_sni})",
        f"# Generated: {now_utc} - DO NOT EDIT MANUALLY",
        "",
        "server {",
        f"    listen {SNI_LOOPBACK_IP}:{int(bridge_port)} ssl;",
        f"    proxy_pass {safe_cs_ip}:{int(stream.cs_port)};",
        "    proxy_connect_timeout 60s;",
        "    proxy_timeout 10m;",
        f"    ssl_certificate {safe_cert};",
        f"    ssl_certificate_key {safe_key};",
        f"    ssl_protocols {safe_protocols};",
        f"    ssl_ciphers {safe_ciphers};",
        "    ssl_session_cache shared:SSL:10m;",
        "    ssl_session_timeout 10m;",
        "    proxy_ssl on;",
        "    proxy_ssl_verify off;",
        "}",
        "",
    ]
    return "\n".join(lines)


def generate_sni_router_config(
    listen_port: int,
    sni_streams: Iterable["StreamConfig"],
    decoy_port: int = SNI_DECOY_PORT,
) -> str:
    """
    Build the outer preread router for one (redirector, listen_port) with
    at least one SNI stream. Returns the text of cyberx_sni_<listen_port>.conf.

    Contains a `map $ssl_preread_server_name $cyberx_p<port>_backend { ... }`
    plus a single `server {} ` block that does `ssl_preread on` and
    `proxy_pass $cyberx_p<port>_backend`. Unmatched SNI (including empty
    SNI) routes to the loopback decoy HTTP server so clients see the
    maintenance page, not a dropped connection.

    Optional outer ACL: if the stream list is non-empty and any entry has
    access_control_enabled=True, the router emits `allow`/`deny` from the
    FIRST such stream's allowed_cidrs. Per-stream ACL on SNI is deliberately
    not supported — preread can't fork different ACLs per hostname without
    a second routing tier, so operators who want different ACLs per SNI
    should use different listen_ports.
    """
    streams = [s for s in sni_streams if getattr(s, "sni_hostname", None)]
    if not streams:
        raise ValueError("generate_sni_router_config called with no SNI streams.")
    if not (1 <= int(listen_port) <= 65535):
        raise ValueError(f"listen_port out of range: {listen_port}")

    # Group by hostname → take the earliest-created stream as authoritative
    # (the DB unique constraint already prevents duplicates, but dedupe
    # defensively so the generator is idempotent on any input ordering).
    by_host: dict[str, "StreamConfig"] = {}
    for s in streams:
        host = _safe_sni_hostname(s.sni_hostname)
        if host not in by_host:
            by_host[host] = s

    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    var_name = f"cyberx_p{int(listen_port)}_backend"

    lines: list[str] = [
        f"# CyberX SNI Router - listen_port={int(listen_port)}",
        f"# Generated: {now_utc} - DO NOT EDIT MANUALLY",
        "",
        f"map $ssl_preread_server_name ${var_name} {{",
        f"    default {SNI_LOOPBACK_IP}:{int(decoy_port)};",
    ]
    for host, s in sorted(by_host.items()):
        bridge = getattr(s, "internal_bridge_port", None)
        if not bridge:
            raise ValueError(
                f"SNI stream {s.id if hasattr(s, 'id') else '?'} "
                f"({host}) has no internal_bridge_port."
            )
        lines.append(f"    {host} {SNI_LOOPBACK_IP}:{int(bridge)};")
    lines.append("}")
    lines.append("")
    lines.append("server {")
    lines.append(f"    listen {int(listen_port)};")
    lines.append("    ssl_preread on;")
    lines.append(f"    proxy_pass ${var_name};")
    lines.append("    proxy_connect_timeout 60s;")
    lines.append("    proxy_timeout 10m;")

    # Outer ACL (first matching stream wins, see docstring)
    for s in streams:
        if s.access_control_enabled and s.allowed_cidrs:
            for cidr in s.allowed_cidrs:
                safe_cidr = _safe_nginx_value(cidr.strip(), "allowed_cidr")
                lines.append(f"    allow {safe_cidr};")
            lines.append("    deny all;")
            break

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Decoy HTTP server (for unmatched SNI on the SNI router)
# ---------------------------------------------------------------------------
#
# The stream preread forwards raw TCP, so we cannot "serve" a page from the
# stream module directly. Unmatched SNI is routed to 127.0.0.1:SNI_DECOY_PORT,
# where an HTTP server block (in nginx http context) terminates TLS with a
# self-signed cert and returns the maintenance HTML. This file goes to
# /etc/nginx/conf.d/cyberx_decoy.conf, which stock Debian/Ubuntu/Kali nginx
# already includes via `include /etc/nginx/conf.d/*.conf;` in http context.

DECOY_CERT_PATH = "/etc/nginx/cyberx/decoy.crt"
DECOY_KEY_PATH = "/etc/nginx/cyberx/decoy.key"
DECOY_CERT_DIR = "/etc/nginx/cyberx"


def generate_decoy_http_config(
    decoy_port: int = SNI_DECOY_PORT,
    cert_path: str = DECOY_CERT_PATH,
    key_path: str = DECOY_KEY_PATH,
) -> str:
    """Return the text of /etc/nginx/conf.d/cyberx_decoy.conf.

    Terminates TLS on 127.0.0.1:<decoy_port> with the redirector's
    self-signed decoy cert and responds to every request with the
    maintenance page. The port binds to loopback only — clients only
    reach it via the outer SNI preread router.
    """
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    html = generate_decoy_html()
    # Escape single quotes for the nginx return directive string. nginx's
    # `return 503 '...'` uses single-quoted strings; we don't expect single
    # quotes in our hand-written HTML, but strip them defensively.
    html_escaped = html.replace("'", "&#39;")
    return (
        "# CyberX SNI Decoy HTTP server\n"
        f"# Generated: {now_utc} - DO NOT EDIT MANUALLY\n"
        "#\n"
        "# Handles unmatched SNI routed from the SNI preread router.\n"
        "# Bound to 127.0.0.1 only; never listens on a public interface.\n"
        "server {\n"
        f"    listen {SNI_LOOPBACK_IP}:{int(decoy_port)} ssl;\n"
        "    server_name _;\n"
        f"    ssl_certificate {cert_path};\n"
        f"    ssl_certificate_key {key_path};\n"
        "    ssl_protocols TLSv1.2 TLSv1.3;\n"
        "    ssl_ciphers HIGH:!aNULL:!MD5;\n"
        "    # Browsers hitting an unknown SNI land here. We return 503 so\n"
        "    # automated scanners also see it as a maintenance page.\n"
        "    location / {\n"
        "        default_type text/html;\n"
        f"        return 503 '{html_escaped}';\n"
        "    }\n"
        "}\n"
    )


def generate_decoy_html() -> str:
    """The static maintenance page shown for unmatched SNI requests.

    Self-contained HTML — no external assets, no fonts, no CDNs. Inline
    SVG for the US and Canadian flags so nothing leaks to the network.
    The tone is intentionally light: this is infra, not customer-facing.
    """
    # Both flags as compact inline SVG. Simplified for size; the canton
    # on the US flag is blank (no stars) and the maple leaf is a stylized
    # path rather than the official 11-point outline.
    us_flag_svg = (
        '<svg viewBox="0 0 190 100" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="United States flag">'
        '<rect width="190" height="100" fill="#b22234"/>'
        '<rect y="7.69" width="190" height="7.69" fill="#fff"/>'
        '<rect y="23.08" width="190" height="7.69" fill="#fff"/>'
        '<rect y="38.46" width="190" height="7.69" fill="#fff"/>'
        '<rect y="53.85" width="190" height="7.69" fill="#fff"/>'
        '<rect y="69.23" width="190" height="7.69" fill="#fff"/>'
        '<rect y="84.62" width="190" height="7.69" fill="#fff"/>'
        '<rect width="76" height="53.85" fill="#3c3b6e"/>'
        '</svg>'
    )
    ca_flag_svg = (
        '<svg viewBox="0 0 200 100" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Canadian flag">'
        '<rect width="200" height="100" fill="#fff"/>'
        '<rect width="50" height="100" fill="#d52b1e"/>'
        '<rect x="150" width="50" height="100" fill="#d52b1e"/>'
        '<path d="M100 18 L106 34 L124 30 L114 46 L132 52 L114 58 L124 74 L106 70 L100 86 L94 70 L76 74 L86 58 L68 52 L86 46 L76 30 L94 34 Z" fill="#d52b1e"/>'
        '</svg>'
    )
    return (
        "<!DOCTYPE html>"
        "<html lang=\"en\">"
        "<head>"
        "<meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
        "<title>Maintenance Mode</title>"
        "<style>"
        "body{font-family:-apple-system,system-ui,Segoe UI,Roboto,sans-serif;"
        "background:#0f1115;color:#e7e9ee;margin:0;padding:48px 24px;text-align:center;}"
        ".wrap{max-width:640px;margin:0 auto;}"
        "h1{font-size:48px;margin:0 0 12px;color:#e4e6ea;font-weight:600;}"
        "h2{font-size:18px;margin:0 0 28px;color:#9ca3af;font-weight:400;}"
        "p{line-height:1.6;color:#cbd5e1;font-size:15px;}"
        ".flags{display:flex;gap:16px;justify-content:center;margin:24px 0 32px;}"
        ".flags svg{width:72px;height:48px;border:1px solid #2a2f3a;border-radius:2px;}"
        ".warn{margin-top:32px;padding:16px 20px;border-left:3px solid #dc2626;"
        "background:#1a0f12;text-align:left;font-size:14px;color:#fca5a5;border-radius:2px;}"
        ".sig{margin-top:24px;color:#6b7280;font-size:13px;font-style:italic;}"
        "</style>"
        "</head>"
        "<body>"
        "<div class=\"wrap\">"
        "<h1>Maintenance Mode</h1>"
        "<h2>The site is temporarily unavailable.</h2>"
        f"<div class=\"flags\">{us_flag_svg}{ca_flag_svg}</div>"
        "<p>"
        "This service is currently offline following an unusually high volume of "
        "<em>&ldquo;have you tried turning it off and on again?&rdquo;</em> attempts "
        "by Blue Team. We are waiting for the power light to blink."
        "</p>"
        "<div class=\"warn\">"
        "<strong>Notice:</strong> Continued engagement with this surface will result "
        "in severe penalties as determined by "
        "<strong>@rtm, CyberX Network Grand Master</strong>, including but not limited "
        "to: immediate assignment to the ICS challenge, mandatory packet-capture "
        "review, and the indefinite loss of break-room microwave privileges."
        "</div>"
        "<div class=\"sig\">&mdash; Posted by @rtm</div>"
        "</div>"
        "</body>"
        "</html>"
    )


def generate_decoy_cert_shell_command(
    cert_path: str = DECOY_CERT_PATH,
    key_path: str = DECOY_KEY_PATH,
    cert_dir: str = DECOY_CERT_DIR,
) -> str:
    """Return the shell command to generate the decoy self-signed cert.

    The SSH service runs this once at deploy-time if the cert doesn't
    already exist. Uses openssl req with -nodes (unencrypted key) and a
    generic CN — clients only ever see this cert when they send an
    unknown SNI, so the common name is cosmetic.
    """
    # Using fixed string literals — no interpolation of user input, so we
    # only need the shell quoting we apply here in our own code.
    return (
        "mkdir -p " + _sh(cert_dir) + " && "
        "chmod 755 " + _sh(cert_dir) + " && "
        "if [ ! -f " + _sh(cert_path) + " ] || [ ! -f " + _sh(key_path) + " ]; then "
        "openssl req -x509 -nodes -newkey rsa:2048 "
        "-subj '/CN=cyberx-redirector-decoy' "
        "-days 3650 "
        "-keyout " + _sh(key_path) + " "
        "-out " + _sh(cert_path) + " "
        "2>/dev/null && "
        "chmod 644 " + _sh(cert_path) + " && "
        "chmod 600 " + _sh(key_path) + "; "
        "fi"
    )


def _sh(val: str) -> str:
    """Minimal shell-quote for static constants used in generated shell lines."""
    if not isinstance(val, str):
        raise ValueError("_sh expects a str")
    if any(c in val for c in "\"'$`\\\n;&|<>"):
        raise ValueError(f"Refusing to shell-quote unsafe value: {val!r}")
    return "'" + val + "'"


def generate_stream_config_preview(stream: "StreamConfig") -> str:
    """Alias for generate_stream_config — used by the preview endpoint."""
    return generate_stream_config(stream)
