"""Pydantic schemas."""
from app.schemas.auth import (
    LoginRequest,
    LoginResponse,
    LogoutResponse,
    UserResponse,
    SessionInfo,
)
from app.schemas.participant import (
    UserRoleEnum,
    ParticipantCreate,
    ParticipantUpdate,
    ParticipantResponse,
    ParticipantListResponse,
    ParticipantStats,
    BulkActionRequest,
    BulkActionResponse,
    PasswordResetRequest,
    PasswordResetResponse,
)
from app.schemas.event import (
    ParticipationStatusEnum,
    EventCreate,
    EventUpdate,
    EventResponse,
    EventListResponse,
    EventParticipationCreate,
    EventParticipationUpdate,
    EventParticipationResponse,
    EventParticipationListResponse,
    BulkInviteRequest,
    BulkInviteResponse,
    ConfirmParticipationRequest,
    ConfirmParticipationResponse,
    ParticipationHistoryResponse,
)
from app.schemas.vpn import (
    VPNCredentialResponse,
    VPNCredentialListResponse,
    VPNStats,
    VPNAssignRequest,
    VPNAssignResponse,
    VPNConfigResponse,
    VPNBulkAssignRequest,
    VPNBulkAssignResponse,
    VPNRequestRequest,
    VPNRequestResponse,
    VPNImportResponse,
    VPNMyCredentialsResponse,
)

__all__ = [
    # Auth
    "LoginRequest",
    "LoginResponse",
    "LogoutResponse",
    "UserResponse",
    "SessionInfo",
    # Participant/Invitee
    "UserRoleEnum",
    "ParticipantCreate",
    "ParticipantUpdate",
    "ParticipantResponse",
    "ParticipantListResponse",
    "ParticipantStats",
    "BulkActionRequest",
    "BulkActionResponse",
    "PasswordResetRequest",
    "PasswordResetResponse",
    # Event & Participation
    "ParticipationStatusEnum",
    "EventCreate",
    "EventUpdate",
    "EventResponse",
    "EventListResponse",
    "EventParticipationCreate",
    "EventParticipationUpdate",
    "EventParticipationResponse",
    "EventParticipationListResponse",
    "BulkInviteRequest",
    "BulkInviteResponse",
    "ConfirmParticipationRequest",
    "ConfirmParticipationResponse",
    "ParticipationHistoryResponse",
    # VPN
    "VPNCredentialResponse",
    "VPNCredentialListResponse",
    "VPNStats",
    "VPNAssignRequest",
    "VPNAssignResponse",
    "VPNConfigResponse",
    "VPNBulkAssignRequest",
    "VPNBulkAssignResponse",
    "VPNRequestRequest",
    "VPNRequestResponse",
    "VPNImportResponse",
    "VPNMyCredentialsResponse",
]
