"""Initial migration with all tables

Revision ID: 2d3773c84f96
Revises: 
Create Date: 2026-01-12 10:56:07.601464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d3773c84f96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sharepoint_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('confirmed', sa.String(length=20), nullable=False),
    sa.Column('email_status', sa.String(length=50), nullable=False),
    sa.Column('email_status_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('future_participation', sa.String(length=20), nullable=True),
    sa.Column('remove_permanently', sa.String(length=20), nullable=True),
    sa.Column('pandas_username', sa.String(length=255), nullable=True),
    sa.Column('pandas_password', sa.String(length=255), nullable=True),
    sa.Column('password_phonetic', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('discord_username', sa.String(length=255), nullable=True),
    sa.Column('snowflake_id', sa.String(length=100), nullable=True),
    sa.Column('discord_invite_code', sa.String(length=50), nullable=True),
    sa.Column('discord_invite_sent', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('invite_id', sa.String(length=50), nullable=True),
    sa.Column('invite_sent', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('invite_reminder_sent', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_invite_sent', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('password_email_sent', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('check_microsoft_email_sent', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('survey_email_sent', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('survey_response_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('orientation_invite_email_sent', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('in_person_email_sent', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('slated_in_person', sa.Boolean(), nullable=True),
    sa.Column('confirmed_in_person', sa.Boolean(), nullable=True),
    sa.Column('sponsor_email', sa.String(length=255), nullable=True),
    sa.Column('azure_object_id', sa.String(length=100), nullable=True),
    sa.Column('pandas_groups', sa.String(length=500), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sharepoint_id')
    )
    op.create_index('idx_users_confirmed', 'users', ['confirmed'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_email_status', 'users', ['email_status'], unique=False)
    op.create_index('idx_users_pandas_username', 'users', ['pandas_username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_pandas_username'), 'users', ['pandas_username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('email_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_to', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('sendgrid_event_id', sa.String(length=255), nullable=True),
    sa.Column('sendgrid_message_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_events_processed', 'email_events', ['processed'], unique=False)
    op.create_index('idx_email_events_type', 'email_events', ['event_type'], unique=False)
    op.create_index('idx_email_events_user_id', 'email_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_email_events_id'), 'email_events', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_token', 'sessions', ['session_token'], unique=False)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_table('vpn_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sharepoint_id', sa.String(length=50), nullable=True),
    sa.Column('interface_ip', sa.Text(), nullable=False),
    sa.Column('ipv4_address', sa.String(length=50), nullable=True),
    sa.Column('ipv6_local', sa.String(length=100), nullable=True),
    sa.Column('ipv6_global', sa.String(length=100), nullable=True),
    sa.Column('private_key', sa.Text(), nullable=False),
    sa.Column('preshared_key', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('key_type', sa.String(length=20), nullable=False),
    sa.Column('assigned_to_username', sa.String(length=255), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('file_id', sa.String(length=50), nullable=True),
    sa.Column('run_id', sa.String(length=100), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sharepoint_id')
    )
    op.create_index('idx_vpn_assigned_to_user_id', 'vpn_credentials', ['assigned_to_user_id'], unique=False)
    op.create_index('idx_vpn_assigned_to_username', 'vpn_credentials', ['assigned_to_username'], unique=False)
    op.create_index('idx_vpn_is_available', 'vpn_credentials', ['is_available'], unique=False)
    op.create_index('idx_vpn_key_type', 'vpn_credentials', ['key_type'], unique=False)
    op.create_index(op.f('ix_vpn_credentials_id'), 'vpn_credentials', ['id'], unique=False)
    op.create_table('vpn_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vpn_credential_id', sa.Integer(), nullable=True),
    sa.Column('key_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('request_source', sa.String(length=50), nullable=True),
    sa.Column('discord_channel_id', sa.String(length=100), nullable=True),
    sa.Column('discord_message_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vpn_credential_id'], ['vpn_credentials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vpn_requests_status', 'vpn_requests', ['status'], unique=False)
    op.create_index('idx_vpn_requests_user_id', 'vpn_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_vpn_requests_id'), 'vpn_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpn_requests_id'), table_name='vpn_requests')
    op.drop_index('idx_vpn_requests_user_id', table_name='vpn_requests')
    op.drop_index('idx_vpn_requests_status', table_name='vpn_requests')
    op.drop_table('vpn_requests')
    op.drop_index(op.f('ix_vpn_credentials_id'), table_name='vpn_credentials')
    op.drop_index('idx_vpn_key_type', table_name='vpn_credentials')
    op.drop_index('idx_vpn_is_available', table_name='vpn_credentials')
    op.drop_index('idx_vpn_assigned_to_username', table_name='vpn_credentials')
    op.drop_index('idx_vpn_assigned_to_user_id', table_name='vpn_credentials')
    op.drop_table('vpn_credentials')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index('idx_sessions_user_id', table_name='sessions')
    op.drop_index('idx_sessions_token', table_name='sessions')
    op.drop_index('idx_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_email_events_id'), table_name='email_events')
    op.drop_index('idx_email_events_user_id', table_name='email_events')
    op.drop_index('idx_email_events_type', table_name='email_events')
    op.drop_index('idx_email_events_processed', table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_pandas_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_pandas_username', table_name='users')
    op.drop_index('idx_users_email_status', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_confirmed', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
