"""add_decline_reason_to_users

Revision ID: ec4255795274
Revises: 20260201_010000
Create Date: 2026-02-01 03:09:05.486346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec4255795274'
down_revision: Union[str, Sequence[str], None] = '20260201_010000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_batch_logs', 'total_processed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('email_batch_logs', 'total_sent',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('email_batch_logs', 'total_failed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('email_batch_logs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('email_batch_logs_batch_id_key', 'email_batch_logs', type_='unique')
    op.drop_index('idx_email_batch_logs_batch_id', table_name='email_batch_logs')
    op.create_index(op.f('ix_email_batch_logs_batch_id'), 'email_batch_logs', ['batch_id'], unique=True)
    op.create_index(op.f('ix_email_batch_logs_id'), 'email_batch_logs', ['id'], unique=False)
    op.alter_column('email_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_email_queue_batch_id', table_name='email_queue')
    op.drop_index('idx_email_queue_created_at', table_name='email_queue')
    op.drop_index('idx_email_queue_priority', table_name='email_queue')
    op.drop_index('idx_email_queue_recipient_email', table_name='email_queue')
    op.drop_index('idx_email_queue_status', table_name='email_queue')
    op.drop_index('idx_email_queue_user_id', table_name='email_queue')
    op.create_index(op.f('ix_email_queue_batch_id'), 'email_queue', ['batch_id'], unique=False)
    op.create_index(op.f('ix_email_queue_created_at'), 'email_queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_queue_id'), 'email_queue', ['id'], unique=False)
    op.create_index(op.f('ix_email_queue_priority'), 'email_queue', ['priority'], unique=False)
    op.create_index(op.f('ix_email_queue_recipient_email'), 'email_queue', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_email_queue_scheduled_for'), 'email_queue', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_email_queue_status'), 'email_queue', ['status'], unique=False)
    op.create_index(op.f('ix_email_queue_user_id'), 'email_queue', ['user_id'], unique=False)
    op.drop_index('idx_workflow_enabled', table_name='email_workflows')
    op.drop_index('idx_workflow_name', table_name='email_workflows')
    op.drop_index('idx_workflow_trigger', table_name='email_workflows')
    op.create_index(op.f('ix_email_workflows_id'), 'email_workflows', ['id'], unique=False)
    op.create_index(op.f('ix_email_workflows_is_enabled'), 'email_workflows', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_email_workflows_name'), 'email_workflows', ['name'], unique=True)
    op.create_index(op.f('ix_email_workflows_trigger_event'), 'email_workflows', ['trigger_event'], unique=False)
    op.drop_index('idx_event_participations_status', table_name='event_participations')
    op.drop_constraint('uq_event_participations_user_event', 'event_participations', type_='unique')
    op.create_index('idx_participation_status', 'event_participations', ['status'], unique=False)
    op.create_index('idx_participation_user_event', 'event_participations', ['user_id', 'event_id'], unique=False)
    op.create_index(op.f('ix_event_participations_status'), 'event_participations', ['status'], unique=False)
    op.create_unique_constraint('uq_user_event', 'event_participations', ['user_id', 'event_id'])
    op.alter_column('events', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('events', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('events', 'confirmation_expires_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.create_index(op.f('ix_events_is_active'), 'events', ['is_active'], unique=False)
    op.add_column('users', sa.Column('decline_reason', sa.String(length=500), nullable=True))
    op.drop_index('idx_users_confirmation_code', table_name='users')
    op.drop_index('idx_users_password_reset_token', table_name='users')
    op.create_index(op.f('ix_users_confirmation_code'), 'users', ['confirmation_code'], unique=True)
    op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_sponsor_id'), 'users', ['sponsor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sponsor_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_confirmation_code'), table_name='users')
    op.create_index('idx_users_password_reset_token', 'users', ['password_reset_token'], unique=True)
    op.create_index('idx_users_confirmation_code', 'users', ['confirmation_code'], unique=True)
    op.drop_column('users', 'decline_reason')
    op.drop_index(op.f('ix_events_is_active'), table_name='events')
    op.alter_column('events', 'confirmation_expires_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('events', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('events', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint('uq_user_event', 'event_participations', type_='unique')
    op.drop_index(op.f('ix_event_participations_status'), table_name='event_participations')
    op.drop_index('idx_participation_user_event', table_name='event_participations')
    op.drop_index('idx_participation_status', table_name='event_participations')
    op.create_unique_constraint('uq_event_participations_user_event', 'event_participations', ['user_id', 'event_id'])
    op.create_index('idx_event_participations_status', 'event_participations', ['status'], unique=False)
    op.drop_index(op.f('ix_email_workflows_trigger_event'), table_name='email_workflows')
    op.drop_index(op.f('ix_email_workflows_name'), table_name='email_workflows')
    op.drop_index(op.f('ix_email_workflows_is_enabled'), table_name='email_workflows')
    op.drop_index(op.f('ix_email_workflows_id'), table_name='email_workflows')
    op.create_index('idx_workflow_trigger', 'email_workflows', ['trigger_event'], unique=False)
    op.create_index('idx_workflow_name', 'email_workflows', ['name'], unique=True)
    op.create_index('idx_workflow_enabled', 'email_workflows', ['is_enabled'], unique=False)
    op.drop_index(op.f('ix_email_queue_user_id'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_status'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_scheduled_for'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_recipient_email'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_priority'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_id'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_created_at'), table_name='email_queue')
    op.drop_index(op.f('ix_email_queue_batch_id'), table_name='email_queue')
    op.create_index('idx_email_queue_user_id', 'email_queue', ['user_id'], unique=False)
    op.create_index('idx_email_queue_status', 'email_queue', ['status'], unique=False)
    op.create_index('idx_email_queue_recipient_email', 'email_queue', ['recipient_email'], unique=False)
    op.create_index('idx_email_queue_priority', 'email_queue', ['priority'], unique=False)
    op.create_index('idx_email_queue_created_at', 'email_queue', ['created_at'], unique=False)
    op.create_index('idx_email_queue_batch_id', 'email_queue', ['batch_id'], unique=False)
    op.alter_column('email_queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_email_batch_logs_id'), table_name='email_batch_logs')
    op.drop_index(op.f('ix_email_batch_logs_batch_id'), table_name='email_batch_logs')
    op.create_index('idx_email_batch_logs_batch_id', 'email_batch_logs', ['batch_id'], unique=False)
    op.create_unique_constraint('email_batch_logs_batch_id_key', 'email_batch_logs', ['batch_id'])
    op.alter_column('email_batch_logs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_batch_logs', 'total_failed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('email_batch_logs', 'total_sent',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('email_batch_logs', 'total_processed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
